### ISSUE TITLE
CodePath iOS Course Project 6 Review

### ISSUE THREAD

**Issue by xlongxl** [dreloong/Instagram#4]
Project 6 is completed. Please review. Thanks! /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Congratulations on finishing the final assignment! It's impressive to realize how far you've come in the first half of the class, going from building a simple tip calculator to a full Instagram app with your own backend.

### Some small comments:
- Awesome job with the submission. The login screen is very nice :star2: 
- It'd be better if you show the alert when signing in with invalid username/password or signing up with the existing user.
- Good usage of `extension` keyword in `CompositionViewController` to make you code clean.
- Great to see your `Home` screen with too many interesting photos instead of the boring default photos in the simulator :wink: 
- I really enjoy your `Profile` screen with the posted photos.

We hope you enjoyed the final assignment. Parse is a great service that makes building a backend app much easier. We have a detailed [Project 6 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_6_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

From here on out there are no more assignments as the focus shifts to the final group project. You'll be working over the next several weeks to build your app idea with your team and then finishing the class with a demo day!
